// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Infrastructure;

namespace api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20190926051114_AddColumn_Transaction_InstallmentsAmount")]
    partial class AddColumn_Transaction_InstallmentsAmount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("api.Model.EntityModel.AdvanceRequest", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("AnalysisResult");

                    b.Property<DateTime?>("DoneAnalysisDate");

                    b.Property<DateTime?>("InitialAnalysisDate");

                    b.Property<DateTime>("InitialDate");

                    b.Property<int>("InstallmentsAmmount");

                    b.Property<int>("Status");

                    b.Property<long>("TransactionId");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("AdvanceRequest");
                });

            modelBuilder.Entity("api.Model.EntityModel.Transaction", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("AcquirerConfirmation");

                    b.Property<int>("CardLastDigits");

                    b.Property<DateTime>("InitialDate");

                    b.Property<int>("InstallmentsAmount");

                    b.Property<double>("TransactionValue");

                    b.Property<DateTime?>("TransferDate");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("api.Model.EntityModel.AdvanceRequest", b =>
                {
                    b.HasOne("api.Model.EntityModel.Transaction", "Transaction")
                        .WithMany("AdvanceRequests")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
